const actionTypes = {
    GET_SEARCH_RESULT_REQUEST: "GET_SEARCH_RESULT_REQUEST",
    GET_SEARCH_RESULT_SUCCESS: "GET_SEARCH_RESULT_SUCCESS",
    GET_SEARCH_RESULT_FAILURE: "GET_SEARCH_RESULT_FAILURE",
    GET_SUGGESTIONS_REQUEST: "GET_SUGGESTIONS_REQUEST",
    GET_SUGGESTIONS_SUCCESS: "GET_SUGGESTIONS_SUCCESS",
    GET_SUGGESTIONS_FAILURE: "GET_SUGGESTIONS_FAILURE",
}

export default actionTypes;